#!/bin/bash
# Phase 3 Manual Test - Instructions for manual verification

echo "=========================================="
echo "PHASE 3 MANUAL VERIFICATION INSTRUCTIONS"
echo "=========================================="
echo ""
echo "The game needs to actually start a new game session for InitGameClock to be called."
echo "This happens after you select 'New Game' from the main menu."
echo ""
echo "STEPS TO VERIFY:"
echo "1. Run: cd /Users/acoliver/projects/uqm/sc2 && ./uqm-debug"
echo "2. Select 'New Game' from the menu (press Enter)"
echo "3. Wait for the game to load (you'll see the intro or gameplay)"
echo "4. Let it run for ~5 seconds (this triggers GameClockTick via hyperspace)"
echo "5. Press ESC or Command-Q to quit"
echo "6. Check the log: cat /Users/acoliver/projects/uqm/sc2/rust-bridge.log"
echo ""
echo "EXPECTED LOG MARKERS:"
echo "  - RUST_BRIDGE_PHASE0_OK (always present)"
echo "  - RUST_FILE_EXISTS_CALLED (file operations during init)"
echo "  - RUST_CLOCK_INIT (when starting a new game)"
echo "  - RUST_CLOCK_TICK (during hyperspace/gameplay)"
echo ""
echo "CURRENT STATUS:"
echo "==============="
echo "Build: SUCCESS (Rust bridge enabled)"
echo "Symbol resolution: SUCCESS"
echo "  - fileExists: Present in binary"
echo "  - InitGameClock: Present in binary"
echo "  - GameClockTick: Present in binary"
echo "Call sites: SUCCESS"
echo "  - fileExists: Called from multiple locations"
echo "  - InitGameClock: Called from starcon.c:218"
echo "Runtime markers: PARTIAL"
echo "  - RUST_BRIDGE_PHASE0_OK: Found"
echo "  - RUST_FILE_EXISTS_CALLED: Found"
echo "  - RUST_CLOCK_INIT: NOT FOUND (needs New Game)"
echo "  - RUST_CLOCK_TICK: NOT FOUND (needs gameplay)"
echo ""
echo "Note: copyFile() is only called in specific scenarios (save games, etc.)"
echo "      and is not expected to appear in a short test run."
