use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    generate_state_bindings(Path::new("../sc2/src/uqm/globdata.h"));

    cc::Build::new()
        .include("../sc2/src")
        .warnings(true)
        .file("../sc2/src/mem_wrapper.c")
        .cpp(false)
        .compile("uqm_core");

    println!("cargo:rerun-if-changed=../sc2/src/mem_wrapper.c");

    // Compile internal helper for uio_vfprintf (not an exported UIO symbol)
    cc::Build::new()
        .warnings(true)
        .file("src/io/uio_vfprintf_helper.c")
        .cpp(false)
        .compile("uio_vfprintf_helper");

    println!("cargo:rerun-if-changed=src/io/uio_vfprintf_helper.c");
}

fn generate_state_bindings(globdata_path: &Path) {
    println!("cargo:rerun-if-changed={}", globdata_path.display());

    let source = fs::read_to_string(globdata_path)
        .expect("failed to read sc2/src/uqm/globdata.h for Rust state bindings");

    let mut bit = 0usize;
    let mut entries = Vec::new();

    for line in source.lines() {
        let Some((name, width)) = parse_game_state_entry(line) else {
            continue;
        };

        let start = bit;
        let end = bit + width - 1;
        entries.push((name, start, end));
        bit += width;
    }

    let num_bits = bit;
    let num_bytes = (num_bits + 7) >> 3;
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    let mut generated = String::new();

    generated.push_str("// @generated by rust/build.rs from sc2/src/uqm/globdata.h\n");
    generated.push_str("// Do not edit by hand.\n\n");
    generated.push_str(&format!(
        "pub const NUM_GAME_STATE_BITS: usize = {num_bits};\n"
    ));
    generated.push_str(&format!(
        "pub const NUM_GAME_STATE_BYTES: usize = {num_bytes};\n\n"
    ));
    generated.push_str("pub fn lookup_game_state_bits(name: &str) -> Option<(usize, usize)> {\n");
    generated.push_str("    match name {\n");

    for (name, start, end) in entries {
        generated.push_str(&format!("        \"{name}\" => Some(({start}, {end})),\n"));
    }

    generated.push_str("        _ => None,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n");

    fs::write(out_dir.join("state_generated.rs"), generated)
        .expect("failed to write generated Rust state bindings");
}

fn parse_game_state_entry(line: &str) -> Option<(String, usize)> {
    let trimmed = line.trim();
    if trimmed.starts_with('#') || !trimmed.contains("ADD_GAME_STATE") {
        return None;
    }

    let open = trimmed.find('(')?;
    let close = trimmed[open + 1..].find(')')? + open + 1;
    let inner = &trimmed[open + 1..close];
    let mut parts = inner.split(',').map(str::trim);

    let name = parts.next()?;
    let width = parts.next()?.parse().ok()?;

    Some((name.to_string(), width))
}
